# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [104]:
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
import pandas as pd

In [105]:
dataframe = pd.read_csv(url)
display(dataframe.head())

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [106]:
columns = dataframe.columns.tolist()
print (columns)

['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value', 'Income', 'Monthly Premium Auto', 'Number of Open Complaints', 'Policy Type', 'Vehicle Class', 'Total Claim Amount']

editing or standardising column names

In [107]:
dataframe.columns = dataframe.columns.str.strip().str.lower().str.replace(" ", "_")
print(dataframe.columns.tolist())

['customer', 'st', 'gender', 'education', 'customer_lifetime_value', 'income', 'monthly_premium_auto', 'number_of_open_complaints', 'policy_type', 'vehicle_class', 'total_claim_amount']

In [108]:
dataframe.dtypes # checking the datatypes of the columns

customer                         str
st                               str
gender                           str
education                        str
customer_lifetime_value          str
income                       float64
monthly_premium_auto         float64
number_of_open_complaints        str
policy_type                      str
vehicle_class                    str
total_claim_amount           float64
dtype: object

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [109]:
print("gender")
print(dataframe["gender"].unique())

print("\nstate")
print(dataframe["st"].unique())

print("\neducation")
print(dataframe["education"].unique())

print("\nvehicle class")
print(dataframe["vehicle_class"].unique())

gender
<ArrowStringArray>
[nan, 'F', 'M', 'Femal', 'Male', 'female']
Length: 6, dtype: str

state
<ArrowStringArray>
['Washington',    'Arizona',     'Nevada', 'California',     'Oregon',
       'Cali',         'AZ',         'WA',          nan]
Length: 9, dtype: str

education
<ArrowStringArray>
[              'Master',             'Bachelor', 'High School or Below',
              'College',            'Bachelors',               'Doctor',
                    nan]
Length: 7, dtype: str

vehicle class
<ArrowStringArray>
['Four-Door Car',  'Two-Door Car',           'SUV',    'Luxury SUV',
    'Sports Car',    'Luxury Car',             nan]
Length: 7, dtype: str

In [110]:
gender_map = {
    "F": "Female", "M": "Male", "Female" : "Female", "Male" : "Male", "female" : "Female", "Femal" : "Female" 
}

dataframe["clean_gender"] = dataframe["gender"].map(gender_map)
display(dataframe["clean_gender"].head())

0       NaN
1    Female
2    Female
3      Male
4      Male
Name: clean_gender, dtype: str

In [111]:
st_map = {
    "Washington" : "Washington", "Arizona" : "Arizona", "Nevada": "Nevada", "California": "California",
    "Oregon" : "Oregon", "Cali" : "California", "AZ" : "Arizona", "WA" : "Washington"
}

dataframe["clean_st"]= dataframe["st"].map(st_map)
display(dataframe["clean_st"].unique())

<ArrowStringArray>
['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', nan]
Length: 6, dtype: str

In [112]:
dataframe["education"] = (dataframe["education"].str.replace("Bachelors", "Bachelor", regex=False)
)
print (dataframe["education"])

0                     Master
1                   Bachelor
2                   Bachelor
3                   Bachelor
4       High School or Below
                ...
4003                     NaN
4004                     NaN
4005                     NaN
4006                     NaN
4007                     NaN
Name: education, Length: 4008, dtype: str

In [113]:
dataframe["education"].unique()

<ArrowStringArray>
['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor', nan]
Length: 6, dtype: str

In [114]:
dataframe["customer_lifetime_value"] = (dataframe["customer_lifetime_value"].str.replace("%", "", regex=False) #this still needs to be converted from strings to numeric since it contains digits
)
print(dataframe["customer_lifetime_value"])

0              NaN
1        697953.59
2       1288743.17
3        764586.18
4        536307.65
           ...
4003           NaN
4004           NaN
4005           NaN
4006           NaN
4007           NaN
Name: customer_lifetime_value, Length: 4008, dtype: str

In [115]:
vehicle_class_map = {
    "Four-Door Car": "Four-Door Car",  "Two-Door Car" : "Two-Door Car", "SUV" : "SUV", "Luxury SUV" : "Luxury",
    "Sports Car" : "Luxury",  "Luxury Car" : "Luxury"
}

dataframe["clean_vehicle_class"] = dataframe["vehicle_class"].map(vehicle_class_map)
print(dataframe["clean_vehicle_class"])

0       Four-Door Car
1       Four-Door Car
2        Two-Door Car
3                 SUV
4       Four-Door Car
            ...
4003              NaN
4004              NaN
4005              NaN
4006              NaN
4007              NaN
Name: clean_vehicle_class, Length: 4008, dtype: str

In [116]:
dataframe["clean_vehicle_class"].unique()

<ArrowStringArray>
['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury', nan]
Length: 5, dtype: str

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [117]:
dataframe["customer_lifetime_value"] = pd.to_numeric(dataframe["customer_lifetime_value"]) # converting from string to numeric and since the column contains a missing value, that is why am using to_numeric
dataframe["customer_lifetime_value"].dtypes

dtype('float64')

In [118]:
dataframe["number_of_open_complaints"].unique()

<ArrowStringArray>
['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan]
Length: 7, dtype: str

In [119]:
dataframe["number_of_open_complaints"] = dataframe["number_of_open_complaints"].str.split("/").str[1] #splitting the digits into 3 parts and selecting the midde digit
display(dataframe["number_of_open_complaints"])

0         0
1         0
2         0
3         0
4         0
       ...
4003    NaN
4004    NaN
4005    NaN
4006    NaN
4007    NaN
Name: number_of_open_complaints, Length: 4008, dtype: object

In [120]:
dataframe["number_of_open_complaints"] = pd.to_numeric(dataframe["number_of_open_complaints"]).astype("Int64") #changing the column datatype to numeric by using to_numeric giving me a float and afterwards using the "Int64" in pandas to change it into integers since the column contains null values .astype(int) does not work

In [121]:
dataframe["number_of_open_complaints"].dtypes

Int64Dtype()

In [122]:
display(dataframe)

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount,clean_gender,clean_st,clean_vehicle_class
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,0,Personal Auto,Four-Door Car,2.704934,NaN,Washington,Four-Door Car
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,0,Personal Auto,Four-Door Car,1131.464935,Female,Arizona,Four-Door Car
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,0,Personal Auto,Two-Door Car,566.472247,Female,Nevada,Two-Door Car
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,0,Corporate Auto,SUV,529.881344,Male,California,SUV
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,0,Personal Auto,Four-Door Car,17.269323,Male,Washington,Four-Door Car
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN

In [123]:
dataframe["number_of_open_complaints"].dtypes

Int64Dtype()

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [ ]:
dataframe.isna().sum() # first i want to know how many null values exist in all the columns

customer                     2937
st                           2937
gender                       3054
education                    2937
customer_lifetime_value      2940
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
clean_gender                 3054
clean_st                     2937
clean_vehicle_class          2937
dtype: int64

First, i would like to drop the rows where all columns in that row has a missing value.

In [ ]:
dataframe = dataframe.dropna(how= "all") # i used this to remove the rows where in each column there is a null or missing values so that my dataframe will be more clearer to read.

In [126]:
display(dataframe)

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount,clean_gender,clean_st,clean_vehicle_class
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,0,Personal Auto,Four-Door Car,2.704934,NaN,Washington,Four-Door Car
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,0,Personal Auto,Four-Door Car,1131.464935,Female,Arizona,Four-Door Car
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,0,Personal Auto,Two-Door Car,566.472247,Female,Nevada,Two-Door Car
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,0,Corporate Auto,SUV,529.881344,Male,California,SUV
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,0,Personal Auto,Four-Door Car,17.269323,Male,Washington,Four-Door Car
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1066,TM65736,Oregon,M,Master,305955.03,38644.0,78.0,1,Personal Auto,Four-Door Car,361.455219,Male,Oregon,Four-Door Car
1067,VJ51327,Cali,F,High School or Below,2031499.76,63209.0,102.0,2,Personal Auto,SUV,207.320041,Female,California,SUV
1068,GS98873,Arizona,F,Bachelor,323912.47,16061.0,88.0,0,Personal Auto,Four-Door Car,633.600000,Female,Arizona,Four-Door Car
1069,CW49887,California,F,Master,462680.11,79487.0,114.0,0,Special Auto,SUV,547.200000,Female,California,SUV
1070,MY31220,California,F,College,899704.02,54230.0,112.0,0,Personal Auto,Two-Door Car,537.600000,Female,California,Two-Door Car

In [127]:
dataframe["customer_lifetime_value"].dtypes

dtype('float64')

In [ ]:
dataframe["customer_lifetime_value"] = dataframe["customer_lifetime_value"]/100 
print(dataframe["customer_lifetime_value"])

0              NaN
1        6979.5359
2       12887.4317
3        7645.8618
4        5363.0765
           ...
1066     3059.5503
1067    20314.9976
1068     3239.1247
1069     4626.8011
1070     8997.0402
Name: customer_lifetime_value, Length: 1071, dtype: float64

In [129]:
dataframe.isna().sum()

customer                       0
st                             0
gender                       117
education                      0
customer_lifetime_value        3
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    0
vehicle_class                  0
total_claim_amount             0
clean_gender                 117
clean_st                       0
clean_vehicle_class            0
dtype: int64

In [131]:
print(dataframe["gender"].unique())

<ArrowStringArray>
[nan, 'F', 'M', 'Femal', 'Male', 'female']
Length: 6, dtype: str

In [ ]:
dataframe_without_missing_gender = dataframe.dropna(subset= ["clean_gender"]) # this is to create a new dataframe where it doesn't contain any missing values in the clean_gender column because it is difficult to determine the exact gender of a particular row. Though i could have the frequency of the gender to determine which one is more and use the highest mode to replace the missing values, i am thinking of the fact that what if that is not the true reflection on ground so to be at a safer side i dropped the missing values for the gender and maintained the ones that were recorded.
display(dataframe_without_missing_gender)

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount,clean_gender,clean_st,clean_vehicle_class
1,QZ44356,Arizona,F,Bachelor,6979.5359,0.0,94.0,0,Personal Auto,Four-Door Car,1131.464935,Female,Arizona,Four-Door Car
2,AI49188,Nevada,F,Bachelor,12887.4317,48767.0,108.0,0,Personal Auto,Two-Door Car,566.472247,Female,Nevada,Two-Door Car
3,WW63253,California,M,Bachelor,7645.8618,0.0,106.0,0,Corporate Auto,SUV,529.881344,Male,California,SUV
4,GA49547,Washington,M,High School or Below,5363.0765,36357.0,68.0,0,Personal Auto,Four-Door Car,17.269323,Male,Washington,Four-Door Car
5,OC83172,Oregon,F,Bachelor,8256.2978,62902.0,69.0,0,Personal Auto,Two-Door Car,159.383042,Female,Oregon,Two-Door Car
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1066,TM65736,Oregon,M,Master,3059.5503,38644.0,78.0,1,Personal Auto,Four-Door Car,361.455219,Male,Oregon,Four-Door Car
1067,VJ51327,Cali,F,High School or Below,20314.9976,63209.0,102.0,2,Personal Auto,SUV,207.320041,Female,California,SUV
1068,GS98873,Arizona,F,Bachelor,3239.1247,16061.0,88.0,0,Personal Auto,Four-Door Car,633.600000,Female,Arizona,Four-Door Car
1069,CW49887,California,F,Master,4626.8011,79487.0,114.0,0,Special Auto,SUV,547.200000,Female,California,SUV
1070,MY31220,California,F,College,8997.0402,54230.0,112.0,0,Personal Auto,Two-Door Car,537.600000,Female,California,Two-Door Car

In [141]:
dataframe_without_missing_gender.isna().sum()

customer                     0
st                           0
gender                       0
education                    0
customer_lifetime_value      2
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
clean_gender                 0
clean_st                     0
clean_vehicle_class          0
dtype: int64

In [143]:
print("maximum value")
print(dataframe_without_missing_gender["customer_lifetime_value"].max())
print("\nminimum value")
print(dataframe_without_missing_gender["customer_lifetime_value"].min())
print("\nmedian value")
print(dataframe_without_missing_gender["customer_lifetime_value"].median())
print("\nmean value")
print(dataframe_without_missing_gender["customer_lifetime_value"].mean())

maximum value
44795.4694

minimum value
2004.3507

median value
5885.7453000000005

mean value
7942.01286302521

Using the median value to fill in the missing values under the customer_lifetime_value

In [144]:
customer_lifetime_median = dataframe_without_missing_gender["customer_lifetime_value"].median()
dataframe_without_missing_gender["customer_lifetime_value"] = dataframe_without_missing_gender["customer_lifetime_value"].fillna(customer_lifetime_median)

In [145]:
dataframe_without_missing_gender.isna().sum()

customer                     0
st                           0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
clean_gender                 0
clean_st                     0
clean_vehicle_class          0
dtype: int64

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [ ]:
dataframe_without_missing_gender.duplicated().sum() # i first check in the dataframe if there are any duplications but there wasnt so there is no need to drop any duplication.

np.int64(0)

In [148]:
cleaned_dataframe = dataframe_without_missing_gender
display(cleaned_dataframe)

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount,clean_gender,clean_st,clean_vehicle_class
1,QZ44356,Arizona,F,Bachelor,6979.5359,0.0,94.0,0,Personal Auto,Four-Door Car,1131.464935,Female,Arizona,Four-Door Car
2,AI49188,Nevada,F,Bachelor,12887.4317,48767.0,108.0,0,Personal Auto,Two-Door Car,566.472247,Female,Nevada,Two-Door Car
3,WW63253,California,M,Bachelor,7645.8618,0.0,106.0,0,Corporate Auto,SUV,529.881344,Male,California,SUV
4,GA49547,Washington,M,High School or Below,5363.0765,36357.0,68.0,0,Personal Auto,Four-Door Car,17.269323,Male,Washington,Four-Door Car
5,OC83172,Oregon,F,Bachelor,8256.2978,62902.0,69.0,0,Personal Auto,Two-Door Car,159.383042,Female,Oregon,Two-Door Car
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1066,TM65736,Oregon,M,Master,3059.5503,38644.0,78.0,1,Personal Auto,Four-Door Car,361.455219,Male,Oregon,Four-Door Car
1067,VJ51327,Cali,F,High School or Below,20314.9976,63209.0,102.0,2,Personal Auto,SUV,207.320041,Female,California,SUV
1068,GS98873,Arizona,F,Bachelor,3239.1247,16061.0,88.0,0,Personal Auto,Four-Door Car,633.600000,Female,Arizona,Four-Door Car
1069,CW49887,California,F,Master,4626.8011,79487.0,114.0,0,Special Auto,SUV,547.200000,Female,California,SUV
1070,MY31220,California,F,College,8997.0402,54230.0,112.0,0,Personal Auto,Two-Door Car,537.600000,Female,California,Two-Door Car

saving the cleaned dataframe in csv format in my current directory

In [150]:
import os
os.getcwd()

'c:\\Users\\yanks\\Documents\\Data Science-Iron hack\\lab-dw-data-cleaning-and-formatting'

In [151]:
cleaned_dataframe.to_csv("cleaned_data.csv", index=False)

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [133]:
# Your code here

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [134]:
# Your code here